# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fib1 = 1
fib2 = 2
sum = fib2
loop do
  fib = fib1 + fib2
  
  if fib % 2 == 0
    sum += fib
  end  

  fib1 = fib2
  fib2 = fib
  break if fib > 4000000
end

puts "Sum of even valued fib numbers < 4,000,000 is: #{sum}"